### ISSUE TITLE
Question: Can 'Membership' tab be restored?

### ISSUE THREAD

**Issue by jeelio** [naasse/CinemaInc#4]
Are tabs dynamic so I put the tab back in? Although we've consolidated the contact forms onto a single page, we may use the membership tab to list discounts members can get with their passes, etc.

I'd like to keep it as a placeholder, and if not used, commented out rather than deleted.

**Comment by naasse** [comment]
Tab is restored. Can be commented out of header.html to hide the tab.
Note: If the file exists on the server, even if it's commented out of header.html, it will be accessible if the user knows the URL.
http://localhost/CinemaInc/membership.html
